# version: '3.9'

services: 

  app:
    build: .
    # restart: unless-stopped
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # networks:
    #   - my-network  
    # depends_on:
    #   - redis
    #   - mongodb 
    ports:
      - "8080:8080"
    env_file:
      - .env

  # redis:
  #   image: redis
  #   container_name: my-redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - my-network 
  #   volumes:
  #     - redis-data:/data

  # mongodb:
  #   image: mongo
  #   container_name: my-mongo
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - my-network 
  #   volumes:
  #     - mongodb-data:/data/db 

# volumes:
#   mongodb-data:
#   redis-data:

# networks:
#   my-network:
#     driver: bridge
