# version: '3.9'

services: 

  # app: 
  #   image: prashantdobariya276813/chatty
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - .env

  # client:
  #   build: ./client
  #   ports:
  #     - "80:80" 
  #   depends_on:
  #     - server
  #   image: prashantdobariya276813/chatty-client:latest
    # restart: unless-stopped
    # build:
    #   context: ./client
    #   dockerfile: Dockerfile
    # networks:
    #   - my-network

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    image: prashantdobariya276813/chatty:latest
    # image: prashantdobariya276813/chatty-server:latest
    # restart: unless-stopped
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # networks:
    #   - my-network  
    # depends_on:
    #   - redis
    #   - mongodb 

  # redis:
  #   image: redis
  #   container_name: my-redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - my-network 
  #   volumes:
  #     - redis-data:/data

  # mongodb:
  #   image: mongo
  #   container_name: my-mongo
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - my-network 
  #   volumes:
  #     - mongodb-data:/data/db 

# volumes:
#   mongodb-data:
#   redis-data:

# networks:
#   my-network:
#     driver: bridge
