services:
  - type: web
    name: server
    env: docker 
    dockerfilePath: ./Dockerfile 
    autoDeploy: true

  - type: web
    name: client
    env: docker 
    dockerfilePath: ./client/Dockerfile
    autoDeploy: true
